project:
  type: website
  
website:
  title: "William W. L. Cheung"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: leadership.qmd
        text: Leadership
      - text: Engagement
        menu:
          - href: training.qmd
            text: Training
          - href: knowledge-mobilization.qmd
            text: Knowledge Mobilization
      - href: contact.qmd
        text: Contact
  
  page-footer:
    center: |
      © 2026 William W. L. Cheung • The University of British Columbia
   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false


